import type { Metadata } from "next";

import "./globals.css";
import Player from "./components/player";
import Sidebar from "./components/ui/sidebar";
import Library from "./components/library";
import Box from "./components/box";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="">
        <div className="h-screen grid grid-flow-row grid-rows-10 gap-1">
          <div className="bg-black row-start-1 row-end-10 grid grid-cols-9 gap-2">
            <div className="col-start-1 col-end-3">
              <Sidebar />
            </div>
            <div className="col-start-3 col-end-10 bg-neutral-900 my-2 rounded-lg">
              {children}
            </div>
          </div>
          <Player className="row-span-1 row-start-10 row-end-10" />
        </div>
      </body>
    </html>
  );
}
